# Generated by Django 5.0.6 on 2024-06-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='type',
            new_name='crop_type',
        ),
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateField(default='2024-06-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='region',
            field=models.CharField(choices=[('central', 'Central'), ('coast', 'Coast'), ('eastern', 'Eastern'), ('nairobi', 'Nairobi'), ('north_eastern', 'North Eastern'), ('nyanza', 'Nyanza'), ('rift_valley', 'Rift Valley'), ('western', 'Western')], max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(choices=[('farms', 'Farm'), ('processing-facilities', 'Processing Facility'), ('distribution-centers', 'Distribution Center'), ('warehouses', 'Warehouse'), ('restaurants', 'Restaurant'), ('supermarkets', 'Supermarket')], max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='fieldmapping.farmer'),
            preserve_default=False,
        ),
    ]
