# Generated by Django 5.0.6 on 2024-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0002_farmer_rename_type_crop_crop_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.AddField(
            model_name='crop',
            name='variety',
            field=models.CharField(default='beans_one', max_length=225),
            preserve_default=False,
        ),
    ]
