# Generated by Django 5.0.6 on 2024-06-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0004_produce_delete_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
