# Generated by Django 5.0.6 on 2024-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0005_delete_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_type', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Crops',
            },
        ),
    ]
