# Generated by Django 5.0.6 on 2024-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0006_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='produce',
            field=models.ManyToManyField(related_name='produce', to='fieldmapping.produce'),
        ),
    ]
