# Generated by Django 5.0.6 on 2024-06-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0007_farm_produce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='fieldmapping.location'),
        ),
    ]
