# Generated by Django 5.0.6 on 2024-06-14 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0009_alter_farm_produce_alter_location_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 2, 41, 58, 363588, tzinfo=datetime.timezone.utc)),
        ),
    ]
