# Generated by Django 5.0.6 on 2024-06-14 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0010_alter_location_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
