# Generated by Django 5.0.6 on 2024-06-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0011_alter_location_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='region',
        ),
    ]
