# Generated by Django 5.0.6 on 2024-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0012_remove_farm_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('central', 'Central'), ('coast', 'Coast'), ('eastern', 'Eastern'), ('nairobi', 'Nairobi'), ('north_eastern', 'North Eastern'), ('nyanza', 'Nyanza'), ('rift_valley', 'Rift Valley'), ('western', 'Western')], default='Nairobi', max_length=100),
            preserve_default=False,
        ),
    ]
