# Generated by Django 5.0.6 on 2024-11-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0014_remove_farm_location_location_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('central', 'Central'), ('coast', 'Coast'), ('eastern', 'Eastern'), ('nairobi', 'Nairobi'), ('north-eastern', 'North Eastern'), ('nyanza', 'Nyanza'), ('rift-valley', 'Rift Valley'), ('western', 'Western')], max_length=100),
        ),
    ]
