# Generated by Django 5.0.6 on 2024-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmapping', '0015_alter_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='area_acres',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
