# Generated by Django 5.0.6 on 2024-06-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('pickup', 'Pickup'), ('canter', 'Canter'), ('lorry', 'Lorry'), ('trailer', 'Trailer')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trackapp.vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trackapp.vehicle'),
            preserve_default=False,
        ),
    ]
