# Generated by Django 5.0.6 on 2024-06-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_vehicle_driver_vehicle_trip_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
