# Generated by Django 5.0.6 on 2024-06-18 15:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0003_remove_trip_route_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trackapp.route'),
            preserve_default=False,
        ),
    ]
