# Generated by Django 5.0.6 on 2024-06-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0004_route_trip_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
